//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gRpcurlUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class GrpcurlSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GrpcurlSetting defaultInstance = ((GrpcurlSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GrpcurlSetting())));
        
        public static GrpcurlSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppSetting {
            get {
                return ((string)(this["AppSetting"]));
            }
            set {
                this["AppSetting"] = value;
            }
        }
    }
}
